version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: marvin
      MYSQL_PASSWORD: azerty123
    ports:
       - 3306
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress.ccft7iqxwiwq.eu-west-1.rds.amazonaws.com
      WORDPRESS_DB_USER: marvin
      WORDPRESS_DB_PASSWORD: azerty123
      WORDPRESS_DB_NAME: wordpress

volumes:
  db_data: {}